import Head from "next/head";
import { analyzeFile } from "@/utils/apiUtils";
import { useMutation } from "react-query";
import { useEffect, useLayoutEffect, useState } from "react";
import { SVGuitarChord } from "svguitar";
import { getChordChart } from "@/lib/cordcharts";

export default function Home() {
  const [chordsUsed, setChordsUsed] = useState<string[] | undefined>(undefined);
  const [file, setFile] = useState<File | null>(null);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files?.length) {
      setFile(event.target.files[0]);
    }
  };

  useEffect(() => {
    if (file) {
      analyzeFileMutation();
    }
  }, [file]);

  const { mutate: analyzeFileMutation } = useMutation(
    async () => analyzeFile(file),
    {
      onSuccess: (response: any) => {
        console.log(response);
        setChordsUsed(response.chordsUsed);
      },
      onError: (error: any) => {
        console.error(error);
      },
    }
  );

  useLayoutEffect(() => {
    console.log(chordsUsed);
    if (!chordsUsed) return;

    let index = 0;
    for (const chord of chordsUsed) {
      const cordchart = getChordChart(chord);
      if (cordchart === undefined) {
        console.log(`No chord chart found for ${chord}`);
      }
      console.log("chart" + index, cordchart);
      try {
        new SVGuitarChord("#chart" + index++)
          .chord(cordchart)
          .configure({ tuning: ["E", "A", "D", "G", "B", "E"] })
          .draw();
      } catch (e) {
        console.error(e);
      }
    }
  }, [chordsUsed]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input type="file" accept=".mp3" onChange={handleFileChange} />
        <div>
          {chordsUsed && (
            <div>
              <h2>Chords used:</h2>
              <ul>
                {chordsUsed.map((chord, index) => (
                  <div
                    key={index}
                    id={"#chart" + index}
                    style={{ maxWidth: "300px" }}
                  ></div>
                ))}
              </ul>
            </div>
          )}
          <div id="chart" style={{ maxWidth: "300px" }}></div>
        </div>
      </div>
    </>
  );
}
